controller_list:
  - name: fake_iris_controller
    joints:
      - /imu_joint
      - rotor_0_joint
      - rotor_1_joint
      - rotor_2_joint
      - rotor_3_joint
  - name: fake_arm_controller
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_hand_controller
    joints:
      - finger_joint1