yolo_model:

  config_file:
    name: human.cfg
  weight_file:
    name: human.weights
  threshold:
    value: 0.8
  detection_classes:
    names:
      - human
      - car
      - fire hydrant
      - street sign
